const express = require('express');
const router = express.Router();

router.post('/generate-summary', async (req, res) => {
  try {
    const { activityData, childName } = req.body;
    
    const siteVisits = activityData.filter(a => 
      a.type === 'SITE_VISIT').length;
    const flagged = activityData.filter(a => 
      a.type === 'CONTENT_FLAGGED').length;
    const blocked = activityData.filter(a => 
      a.type === 'SITE_BLOCKED' || 
      a.type === 'SEARCH_BLOCKED').length;
    const panics = activityData.filter(a => 
      a.type === 'PANIC').length;

    const score = Math.max(1, Math.min(10, 
      10 - (flagged * 0.5) - (blocked * 1) - 
      (panics * 2)));
    const roundedScore = Math.round(score);

    let assessment = "";
    let concerns = "";
    let praise = "";
    let recommendations = "";

    if (roundedScore >= 8) {
      assessment = `${childName} had an excellent week online! 🌟 They showed great browsing habits and stayed safe throughout.`;
      praise = `💪 Amazing self-control! ${childName} visited ${siteVisits} sites with minimal issues.`;
    } else if (roundedScore >= 6) {
      assessment = `${childName} had a pretty good week overall! 😊 There were a few bumps but nothing too concerning.`;
      praise = `✅ Good effort! ${childName} visited ${siteVisits} sites and stayed safe most of the time.`;
    } else {
      assessment = `${childName} had a challenging week online. 💙 Let's work together to improve next week!`;
      praise = `🌈 Every day is a new opportunity! ${childName} did visit ${siteVisits} sites safely.`;
    }

    if (flagged > 0 || blocked > 0) {
      concerns = `⚠️ Areas to watch: ${blocked} inappropriate searches were blocked and content was flagged ${flagged} times. Consider having a conversation about safe browsing.`;
    } else {
      concerns = `✨ No major concerns this week! Keep up the great work!`;
    }

    if (panics > 0) {
      concerns += ` 🚨 The panic button was pressed ${panics} time(s) — make sure to check in with ${childName} about what they saw.`;
    }

    recommendations = `🎯 Recommendations:
1. ${siteVisits > 100 ? `Consider reducing daily screen time — ${childName} visited ${siteVisits} sites this week.` : `Screen time looks healthy at ${siteVisits} sites this week. Keep it up!`}
2. ${flagged > 2 ? 'Have a friendly chat about what content is appropriate online.' : 'Keep encouraging safe browsing habits with positive reinforcement.'}
3. Add more educational sites to ${childName}'s recommended sites list to guide their curiosity in the right direction! 📚`;

    const summary = `📊 Weekly Summary for ${childName}

${assessment}

${concerns}

${praise}

${recommendations}

⭐ Overall Score: ${roundedScore}/10 — ${roundedScore >= 8 ? 'Outstanding! 🏆' : roundedScore >= 6 ? 'Good job! 😊' : 'Keep improving! 💪'}

Generated by SafeWeb Jr AI`;

    // Simulate AI thinking time
    await new Promise(resolve => setTimeout(resolve, 2000));

    res.json({ 
      summary,
      stats: { siteVisits, flagged, blocked, panics }
    });

  } catch (error) {
    console.error('Summary error:', error.message);
    res.status(500).json({ error: error.message });
  }
});

module.exports = router;
